import js from '@eslint/js';
import { configs as tseslintConfigs } from 'typescript-eslint';
import prettierConfig from 'eslint-config-prettier';
import { importX } from 'eslint-plugin-import-x';

export default [
  js.configs.recommended,
  ...tseslintConfigs.recommended,
  importX.flatConfigs.recommended,
  importX.flatConfigs.typescript,
  prettierConfig,
  {
    ignores: [
      '**/dist/**',
      '**/dist-types/**',
      '**/node_modules/**',
      // Generated/vendor files that shouldn't be linted
      '**/pdfjs.js',
      '**/worker.js',
      '**/pdfjs-worker.js',
      '**/*.min.js',
      '**/vendor/**',
      '**/lib/**/*.umd.js',
      'packages/preset-geometry/**',
      // Generated TypeScript declaration files (auto-generated by tsc)
      '**/src/**/*.d.ts',
      '**/src/**/*.d.ts.map',
      // Test files
      '**/*.test.js',
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.js',
      '**/tests/**',
      '**/test/**',
      // Docs (Mintlify site with its own conventions)
      'apps/docs/**',
      // Examples (different environments and coding styles)
      'examples/**',
      '**/examples/**',
      // Demos (different environments and dependency sets)
      'demos/**',
      '**/demos/**',
      // Config files (CommonJS/different environments)
      '**/*.config.js',
      '**/*.cjs',
      '**/commitlint.config.js',
      // E2E tests
      'e2e-tests/**',
      // SDK scripts — ESM parsed incorrectly by typescript-eslint
      'packages/sdk/scripts/**',
    ],
  },
  {
    settings: {
      'import-x/resolver': {
        // Prefer repo source entrypoints during lint so workspace packages do
        // not depend on generated dist artifacts before the build step runs.
        node: {
          conditionNames: ['source', 'import', 'require', 'node', 'default'],
          mainFields: ['source', 'module', 'main'],
        },
        typescript: {
          conditionNames: ['source', 'types', 'import', 'require', 'node', 'default'],
          mainFields: ['source', 'module', 'main'],
        },
      },
    },
  },
  {
    languageOptions: {
      // Globals for mixed browser/Node.js codebase
      globals: {
        // Universal APIs (available in both environments)
        console: 'readonly',
        fetch: 'readonly',
        AbortSignal: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',

        // Browser APIs (client-side code)
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        File: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        DOMParser: 'readonly',
        atob: 'readonly',
        screen: 'readonly',
        requestAnimationFrame: 'readonly',
        URLSearchParams: 'readonly',
        TextDecoder: 'readonly',
        FileReader: 'readonly',
        DOMRect: 'readonly',

        // DOM APIs (text editing, clipboard, elements)
        HTMLElement: 'readonly',
        Node: 'readonly',
        DataTransfer: 'readonly',
        ClipboardEvent: 'readonly',
        TextSelection: 'readonly',
        CustomEvent: 'readonly',

        // Prosemirror library APIs
        ReplaceAroundStep: 'readonly',
        mergeAttributes: 'readonly',
        splitCell: 'readonly',

        // Utility functions and constants
        dateFormat: 'readonly',
        fontSize: 'readonly',
        nodeListHandler: 'readonly',
        node: 'readonly',

        // Node.js APIs (server-side code)
        Buffer: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
        global: 'readonly',

        // Build constants
        __IS_DEBUG__: 'readonly',
        __APP_VERSION__: 'readonly',
        version: 'readonly',
        superdoc: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }], // See warnings but don't block

      // Relax these rules - they're more style than bugs
      'no-empty': ['warn', { allowEmptyCatch: true }], // Allow empty catch blocks
      'no-case-declarations': 'off', // Common pattern in switch statements
      'no-control-regex': 'off', // Sometimes needed for text processing
      'no-useless-escape': 'warn', // Warn but don't error

      // Keep as warnings to address gradually
      'no-unsafe-optional-chaining': 'warn', // Important but not critical
      'no-unused-private-class-members': 'warn', // Clean up when refactoring

      // Prevent imports across package boundaries
      'import-x/no-relative-packages': [
        'error',
        {
          // Allow importing top-level vitest.baseConfig and vite.sourceResolve
          ignore: [
            '^.*/vitest.baseConfig$',
            '^.*/vite.sourceResolve$',
          ],
        }
      ],

      'import-x/no-unresolved': [
        'error',
        {
          // Temporarily all "@"-prefixed imports. This should likely be changed to use https://github.com/pzmosquito/eslint-import-resolver-vite to properly resolve these aliases
          ignore: [
            '^@.*$',
            '^bun:.*$', // Bun built-in modules
            '^superdoc$',
            '^superdoc/.*$',
            '^\\..*/generated/', // Generated files (codegen artifacts, not in git)
          ],
        }
      ]
    },
  },
  // TypeScript-specific configuration
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // TypeScript handles these better than ESLint
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],

      // Relax some TypeScript rules for incremental adoption
      '@typescript-eslint/no-explicit-any': 'warn', // Gradually remove 'any'
      '@typescript-eslint/no-non-null-assertion': 'off', // Used carefully in adapters
      '@typescript-eslint/no-empty-function': 'warn', // Allow for test mocks
    },
  },
  // Mock files configuration (JavaScript files in __mocks__ directories)
  {
    files: ['**/__mocks__/**/*.js'],
    rules: {
      // Disable TypeScript rule for JavaScript mock files
      '@typescript-eslint/no-unused-vars': 'off',
      // JavaScript rule with underscore pattern already applied
    },
  },
  // Parts boundary enforcement: prevent direct writes to convertedXml outside part-store.ts
  {
    files: [
      'packages/super-editor/src/editors/v1/**/*.ts',
      'packages/super-editor/src/editors/v1/**/*.js',
    ],
    ignores: [
      'packages/super-editor/src/editors/v1/core/parts/store/part-store.ts',
      // Test helpers set up mock convertedXml for part tests
      'packages/super-editor/src/editors/v1/core/parts/testing/**',
      // Import/export phases are exempt (initial document load and final export)
      'packages/super-editor/src/editors/v1/core/super-converter/**',
      // Validator normalizes rels key paths during document load
      'packages/super-editor/src/editors/v1/core/super-validator/**',
    ],
    rules: {
      'no-restricted-syntax': [
        'warn',
        {
          selector: "AssignmentExpression > MemberExpression[property.name='convertedXml']",
          message:
            'Direct assignment to convertedXml is prohibited. Use setPart/removePart from core/parts/store/part-store.ts, or mutatePart/mutateParts for mutations.',
        },
        {
          selector: "AssignmentExpression > MemberExpression[object.property.name='convertedXml'][computed=true]",
          message:
            'Direct assignment to convertedXml[...] is prohibited. Use setPart/removePart from core/parts/store/part-store.ts, or mutatePart/mutateParts for mutations.',
        },
      ],
    },
  },
  {
    files: ['packages/super-editor/src/editors/v1/extensions/**/*.js'],
    rules: {
      '@typescript-eslint/ban-ts-comment': 'off',
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    files: ['packages/super-editor/src/editors/v1/extensions/types/**/*.ts'],
    rules: {
      '@typescript-eslint/no-empty-object-type': [
        'off',
        {
          allowInterfacesWithSingleExtends: true,
        },
      ],
    },
  },
  {
    files: ['packages/super-editor/src/editors/v1/core/types/ChainedCommands.ts'],
    rules: {
      // These empty interfaces are intentionally used for declaration merging
      // Extensions augment them via module augmentation to add typed commands
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
];
