/**
 * CLI-local metadata for each exposed doc-backed operation.
 *
 * Drives the generic dispatch path — orchestrator selection, success messaging,
 * output formatting, response envelope key, and error-mapping family.
 *
 * All tables are keyed by CliExposedOperationId. A missing entry is a compile
 * error — TypeScript enforces completeness. When a new operation is added to
 * OPERATION_DEFINITIONS, the CLI requires only a one-line entry in each table.
 */

import { COMMAND_CATALOG, INLINE_PROPERTY_REGISTRY, type InlineRunPatchKey } from '@superdoc/document-api';
import type { CliExposedOperationId } from './operation-set.js';

type FormatInlineAliasOperationId = `format.${InlineRunPatchKey}`;

const FORMAT_INLINE_ALIAS_OPERATION_IDS = INLINE_PROPERTY_REGISTRY.map(
  (entry) => `format.${entry.key}` as FormatInlineAliasOperationId,
);

function buildFormatInlineAliasRecord<T>(value: T): Record<FormatInlineAliasOperationId, T> {
  return Object.fromEntries(FORMAT_INLINE_ALIAS_OPERATION_IDS.map((operationId) => [operationId, value])) as Record<
    FormatInlineAliasOperationId,
    T
  >;
}

const PARAGRAPH_OPERATION_IDS = [
  'styles.paragraph.setStyle',
  'styles.paragraph.clearStyle',
  'format.paragraph.resetDirectFormatting',
  'format.paragraph.setAlignment',
  'format.paragraph.clearAlignment',
  'format.paragraph.setIndentation',
  'format.paragraph.clearIndentation',
  'format.paragraph.setSpacing',
  'format.paragraph.clearSpacing',
  'format.paragraph.setKeepOptions',
  'format.paragraph.setOutlineLevel',
  'format.paragraph.setFlowOptions',
  'format.paragraph.setTabStop',
  'format.paragraph.clearTabStop',
  'format.paragraph.clearAllTabStops',
  'format.paragraph.setBorder',
  'format.paragraph.clearBorder',
  'format.paragraph.setShading',
  'format.paragraph.clearShading',
] as const satisfies readonly CliExposedOperationId[];

type ParagraphOperationId = (typeof PARAGRAPH_OPERATION_IDS)[number];

function buildParagraphRecord<T>(value: T): Record<ParagraphOperationId, T> {
  return Object.fromEntries(PARAGRAPH_OPERATION_IDS.map((operationId) => [operationId, value])) as Record<
    ParagraphOperationId,
    T
  >;
}

// ---------------------------------------------------------------------------
// Orchestration kind (derived from COMMAND_CATALOG)
// ---------------------------------------------------------------------------

/** Which orchestrator to use: read or mutation. Derived from COMMAND_CATALOG. */
export function orchestrationKind(opId: CliExposedOperationId): 'read' | 'mutation' {
  return COMMAND_CATALOG[opId].mutates ? 'mutation' : 'read';
}

// ---------------------------------------------------------------------------
// Success verb (past-tense for pretty output)
// ---------------------------------------------------------------------------

/** Past-tense verb for success messages. */
export const SUCCESS_VERB: Record<CliExposedOperationId, string> = {
  get: 'retrieved document',
  markdownToFragment: 'converted markdown to fragment',
  find: 'completed search',
  getNode: 'resolved node',
  getNodeById: 'resolved node',
  getText: 'extracted text',
  getMarkdown: 'extracted markdown',
  getHtml: 'extracted html',
  info: 'retrieved info',
  extract: 'extracted content',
  clearContent: 'cleared document content',
  insert: 'inserted text',
  replace: 'replaced text',
  delete: 'deleted text',
  'blocks.list': 'listed blocks',
  'blocks.delete': 'deleted block',
  'blocks.deleteRange': 'deleted block range',
  formatRange: 'applied style',
  'format.apply': 'applied style',
  ...buildFormatInlineAliasRecord('applied style'),
  ...buildParagraphRecord('updated paragraph formatting'),
  'styles.apply': 'applied stylesheet defaults',
  'templates.apply': 'applied template substrate',
  'create.paragraph': 'created paragraph',
  'create.heading': 'created heading',
  'create.tableOfContents': 'created table of contents',
  'lists.list': 'listed items',
  'lists.get': 'resolved list item',
  'lists.insert': 'inserted list item',
  'lists.indent': 'indented list item',
  'lists.outdent': 'outdented list item',
  'lists.create': 'created list',
  'lists.attach': 'attached to list',
  'lists.detach': 'detached from list',
  'lists.join': 'joined lists',
  'lists.canJoin': 'checked join feasibility',
  'lists.separate': 'separated list',
  'lists.setLevel': 'set list level',
  'lists.setValue': 'set list value',
  'lists.continuePrevious': 'continued previous list',
  'lists.canContinuePrevious': 'checked continue feasibility',
  'lists.setLevelRestart': 'set level restart',
  'lists.applyTemplate': 'applied list template',
  'lists.applyPreset': 'applied list preset',
  'lists.captureTemplate': 'captured list template',
  'lists.setLevelNumbering': 'set level numbering',
  'lists.setLevelBullet': 'set level bullet',
  'lists.setLevelPictureBullet': 'set level picture bullet',
  'lists.setLevelAlignment': 'set level alignment',
  'lists.setLevelIndents': 'set level indents',
  'lists.setLevelTrailingCharacter': 'set level trailing character',
  'lists.setLevelMarkerFont': 'set level marker font',
  'lists.clearLevelOverrides': 'cleared level overrides',
  'lists.convertToText': 'converted list to text',
  'comments.create': 'created comment',
  'comments.patch': 'patched comment',
  'comments.delete': 'deleted comment',
  'comments.get': 'resolved comment',
  'comments.list': 'listed comments',
  'trackChanges.list': 'listed tracked changes',
  'trackChanges.get': 'resolved tracked change',
  'trackChanges.decide': 'reviewed tracked change',
  'toc.list': 'listed tables of contents',
  'toc.get': 'resolved table of contents',
  'toc.configure': 'configured table of contents',
  'toc.update': 'updated table of contents',
  'toc.remove': 'removed table of contents',
  'toc.markEntry': 'marked table of contents entry',
  'toc.unmarkEntry': 'unmarked table of contents entry',
  'toc.listEntries': 'listed table of contents entries',
  'toc.getEntry': 'resolved table of contents entry',
  'toc.editEntry': 'edited table of contents entry',
  'query.match': 'matched selectors',
  'mutations.preview': 'previewed mutations',
  'mutations.apply': 'applied mutations',
  'capabilities.get': 'retrieved capabilities',

  // Tables
  'create.table': 'created table',
  'tables.convertFromText': 'converted text to table',
  'tables.delete': 'deleted table',
  'tables.clearContents': 'cleared table contents',
  'tables.move': 'moved table',
  'tables.split': 'split table',
  'tables.convertToText': 'converted table to text',
  'tables.setLayout': 'updated table layout',
  'tables.insertRow': 'inserted row',
  'tables.deleteRow': 'deleted row',
  'tables.setRowHeight': 'set row height',
  'tables.distributeRows': 'distributed rows',
  'tables.setRowOptions': 'set row options',
  'tables.insertColumn': 'inserted column',
  'tables.deleteColumn': 'deleted column',
  'tables.setColumnWidth': 'set column width',
  'tables.distributeColumns': 'distributed columns',
  'tables.insertCell': 'inserted cell',
  'tables.deleteCell': 'deleted cell',
  'tables.mergeCells': 'merged cells',
  'tables.unmergeCells': 'unmerged cells',
  'tables.splitCell': 'split cell',
  'tables.setCellProperties': 'set cell properties',
  'tables.sort': 'sorted table',
  'tables.setAltText': 'set alt text',
  'tables.setStyle': 'set table style',
  'tables.clearStyle': 'cleared table style',
  'tables.setStyleOption': 'set style option',
  'tables.setBorder': 'set border',
  'tables.clearBorder': 'cleared border',
  'tables.applyBorderPreset': 'applied border preset',
  'tables.setShading': 'set shading',
  'tables.clearShading': 'cleared shading',
  'tables.setTablePadding': 'set table padding',
  'tables.setCellPadding': 'set cell padding',
  'tables.setCellSpacing': 'set cell spacing',
  'tables.clearCellSpacing': 'cleared cell spacing',
  'tables.get': 'resolved table',
  'tables.getCells': 'listed cells',
  'tables.getProperties': 'resolved table properties',
  'tables.getStyles': 'listed table styles',
  'tables.setDefaultStyle': 'set default table style',
  'tables.clearDefaultStyle': 'cleared default table style',
  'history.get': 'retrieved history state',
  'history.undo': 'undid last change',
  'history.redo': 'redid last change',

  // Images
  'create.image': 'created image',
  'images.list': 'listed images',
  'images.get': 'resolved image',
  'images.delete': 'deleted image',
  'images.move': 'moved image',
  'images.convertToInline': 'converted to inline',
  'images.convertToFloating': 'converted to floating',
  'images.setSize': 'set image size',
  'images.setWrapType': 'set wrap type',
  'images.setWrapSide': 'set wrap side',
  'images.setWrapDistances': 'set wrap distances',
  'images.setPosition': 'set position',
  'images.setAnchorOptions': 'set anchor options',
  'images.setZOrder': 'set z-order',

  // Diff
  'diff.capture': 'captured snapshot',
  'diff.compare': 'compared documents',
  'diff.apply': 'applied diff',

  // Every doc-api operation must have a success verb.
  // Used only by `--pretty` output; JSON envelope unaffected.
  'authorities.configure': 'configured',
  'authorities.entries.get': 'retrieved item',
  'authorities.entries.insert': 'inserted item',
  'authorities.entries.list': 'listed items',
  'authorities.entries.remove': 'removed item',
  'authorities.entries.update': 'updated item',
  'authorities.get': 'retrieved item',
  'authorities.insert': 'inserted item',
  'authorities.list': 'listed items',
  'authorities.rebuild': 'rebuilt',
  'authorities.remove': 'removed item',
  'bookmarks.get': 'retrieved item',
  'bookmarks.insert': 'inserted item',
  'bookmarks.list': 'listed items',
  'bookmarks.remove': 'removed item',
  'bookmarks.rename': 'renamed item',
  'captions.configure': 'configured',
  'captions.get': 'retrieved item',
  'captions.insert': 'inserted item',
  'captions.list': 'listed items',
  'captions.remove': 'removed item',
  'captions.update': 'updated item',
  'citations.bibliography.configure': 'configured',
  'citations.bibliography.get': 'retrieved item',
  'citations.bibliography.insert': 'inserted item',
  'citations.bibliography.rebuild': 'rebuilt',
  'citations.bibliography.remove': 'removed item',
  'citations.get': 'retrieved item',
  'citations.insert': 'inserted item',
  'citations.list': 'listed items',
  'citations.remove': 'removed item',
  'citations.sources.get': 'retrieved item',
  'citations.sources.insert': 'inserted item',
  'citations.sources.list': 'listed items',
  'citations.sources.remove': 'removed item',
  'citations.sources.update': 'updated item',
  'citations.update': 'updated item',
  'contentControls.appendContent': 'appended content',
  'contentControls.checkbox.getState': 'retrieved state',
  'contentControls.checkbox.setState': 'updated state',
  'contentControls.checkbox.setSymbolPair': 'updated symbol pair',
  'contentControls.checkbox.toggle': 'toggled checkbox',
  'contentControls.choiceList.getItems': 'retrieved items',
  'contentControls.choiceList.setItems': 'updated items',
  'contentControls.choiceList.setSelected': 'updated selected',
  'contentControls.clearBinding': 'cleared binding',
  'contentControls.clearContent': 'cleared content',
  'contentControls.copy': 'copied item',
  'contentControls.date.clearValue': 'cleared value',
  'contentControls.date.setCalendar': 'updated calendar',
  'contentControls.date.setDisplayFormat': 'updated display format',
  'contentControls.date.setDisplayLocale': 'updated display locale',
  'contentControls.date.setStorageFormat': 'updated storage format',
  'contentControls.date.setValue': 'updated value',
  'contentControls.delete': 'deleted item',
  'contentControls.get': 'retrieved item',
  'contentControls.getBinding': 'retrieved binding',
  'contentControls.getContent': 'retrieved content',
  'contentControls.getParent': 'retrieved parent',
  'contentControls.getRawProperties': 'retrieved raw properties',
  'contentControls.group.ungroup': 'ungrouped',
  'contentControls.group.wrap': 'wrapped group',
  'contentControls.insertAfter': 'inserted after',
  'contentControls.insertBefore': 'inserted before',
  'contentControls.list': 'listed items',
  'contentControls.listChildren': 'listed children',
  'contentControls.listInRange': 'listed in range',
  'contentControls.move': 'moved item',
  'contentControls.normalizeTagPayload': 'normalized tag payload',
  'contentControls.normalizeWordCompatibility': 'normalized word compatibility',
  'contentControls.patch': 'patched item',
  'contentControls.patchRawProperties': 'patched raw properties',
  'contentControls.prependContent': 'prepended content',
  'contentControls.repeatingSection.cloneItem': 'cloned item',
  'contentControls.repeatingSection.deleteItem': 'deleted item',
  'contentControls.repeatingSection.insertItemAfter': 'inserted item after',
  'contentControls.repeatingSection.insertItemBefore': 'inserted item before',
  'contentControls.repeatingSection.listItems': 'listed items',
  'contentControls.repeatingSection.setAllowInsertDelete': 'updated allow insert delete',
  'contentControls.replaceContent': 'replaced content',
  'contentControls.selectByTag': 'selected by tag',
  'contentControls.selectByTitle': 'selected by title',
  'contentControls.setBinding': 'updated binding',
  'contentControls.setLockMode': 'updated lock mode',
  'contentControls.setType': 'updated type',
  'contentControls.text.clearValue': 'cleared value',
  'contentControls.text.setMultiline': 'updated multiline',
  'contentControls.text.setValue': 'updated value',
  'contentControls.unwrap': 'unwrapped',
  'contentControls.validateWordCompatibility': 'validated word compatibility',
  'contentControls.wrap': 'wrapped',
  'create.contentControl': 'created content control',
  'create.sectionBreak': 'created section break',
  'crossRefs.get': 'retrieved item',
  'crossRefs.insert': 'inserted item',
  'crossRefs.list': 'listed items',
  'crossRefs.rebuild': 'rebuilt',
  'crossRefs.remove': 'removed item',
  'customXml.parts.create': 'created item',
  'customXml.parts.get': 'retrieved item',
  'customXml.parts.list': 'listed items',
  'customXml.parts.patch': 'patched item',
  'customXml.parts.remove': 'removed item',
  'fields.get': 'retrieved item',
  'fields.insert': 'inserted item',
  'fields.list': 'listed items',
  'fields.rebuild': 'rebuilt',
  'fields.remove': 'removed item',
  'footnotes.configure': 'configured',
  'footnotes.get': 'retrieved item',
  'footnotes.insert': 'inserted item',
  'footnotes.list': 'listed items',
  'footnotes.remove': 'removed item',
  'footnotes.update': 'updated item',
  'format.paragraph.clearDirection': 'cleared direction',
  'format.paragraph.setDirection': 'updated direction',
  'headerFooters.get': 'retrieved item',
  'headerFooters.list': 'listed items',
  'headerFooters.parts.create': 'created item',
  'headerFooters.parts.delete': 'deleted item',
  'headerFooters.parts.list': 'listed items',
  'headerFooters.refs.clear': 'cleared ref',
  'headerFooters.refs.set': 'updated ref',
  'headerFooters.refs.setLinkedToPrevious': 'updated linked to previous',
  'headerFooters.resolve': 'resolved',
  'hyperlinks.get': 'retrieved item',
  'hyperlinks.insert': 'inserted item',
  'hyperlinks.list': 'listed items',
  'hyperlinks.patch': 'patched item',
  'hyperlinks.remove': 'removed item',
  'hyperlinks.wrap': 'wrapped',
  'images.crop': 'cropped image',
  'images.flip': 'flipped image',
  'images.insertCaption': 'inserted caption',
  'images.removeCaption': 'removed caption',
  'images.replaceSource': 'replaced source',
  'images.resetCrop': 'reset crop',
  'images.rotate': 'rotated image',
  'images.scale': 'scaled image',
  'images.setAltText': 'updated alt text',
  'images.setDecorative': 'updated decorative',
  'images.setHyperlink': 'updated hyperlink',
  'images.setLockAspectRatio': 'updated lock aspect ratio',
  'images.setName': 'updated name',
  'images.updateCaption': 'updated caption',
  'index.configure': 'configured',
  'index.entries.get': 'retrieved item',
  'index.entries.insert': 'inserted item',
  'index.entries.list': 'listed items',
  'index.entries.remove': 'removed item',
  'index.entries.update': 'updated item',
  'index.get': 'retrieved item',
  'index.insert': 'inserted item',
  'index.list': 'listed items',
  'index.rebuild': 'rebuilt',
  'index.remove': 'removed item',
  'lists.applyStyle': 'applied style',
  'lists.delete': 'deleted item',
  'lists.getStyle': 'retrieved style',
  'lists.merge': 'merged lists',
  'lists.restartAt': 'restarted numbering',
  'lists.setLevelLayout': 'updated level layout',
  'lists.setLevelNumberStyle': 'updated level number style',
  'lists.setLevelStart': 'updated level start',
  'lists.setLevelText': 'updated level text',
  'lists.setType': 'updated type',
  'lists.split': 'split list',
  'metadata.attach': 'attached metadata',
  'metadata.get': 'retrieved item',
  'metadata.list': 'listed items',
  'metadata.remove': 'removed item',
  'metadata.resolve': 'resolved metadata',
  'metadata.update': 'updated item',
  'permissionRanges.create': 'created item',
  'permissionRanges.get': 'retrieved item',
  'permissionRanges.list': 'listed items',
  'permissionRanges.remove': 'removed item',
  'permissionRanges.updatePrincipal': 'updated principal',
  'protection.clearEditingRestriction': 'cleared editing restriction',
  'protection.get': 'retrieved item',
  'protection.setEditingRestriction': 'updated editing restriction',
  'ranges.resolve': 'resolved range',
  'sections.clearHeaderFooterRef': 'cleared header footer ref',
  'sections.clearPageBorders': 'cleared page borders',
  'sections.get': 'retrieved item',
  'sections.list': 'listed items',
  'sections.setBreakType': 'updated break type',
  'sections.setColumns': 'updated columns',
  'sections.setHeaderFooterMargins': 'updated header footer margins',
  'sections.setHeaderFooterRef': 'updated header footer ref',
  'sections.setLineNumbering': 'updated line numbering',
  'sections.setLinkToPrevious': 'updated link to previous',
  'sections.setOddEvenHeadersFooters': 'updated odd even headers footers',
  'sections.setPageBorders': 'updated page borders',
  'sections.setPageMargins': 'updated page margins',
  'sections.setPageNumbering': 'updated page numbering',
  'sections.setPageSetup': 'updated page setup',
  'sections.setSectionDirection': 'updated section direction',
  'sections.setTitlePage': 'updated title page',
  'sections.setVerticalAlign': 'updated vertical align',
  'selection.current': 'retrieved current selection',
  'tables.applyPreset': 'applied table preset',
  'tables.applyStyle': 'applied table style',
  'tables.setBorders': 'updated borders',
  'tables.setCellText': 'updated cell text',
  'tables.setTableOptions': 'updated table options',
};

// ---------------------------------------------------------------------------
// Output format (selects the pretty-printer)
// ---------------------------------------------------------------------------

export type OutputFormat =
  | 'queryResult'
  | 'nodeInfo'
  | 'mutationReceipt'
  | 'createResult'
  | 'listResult'
  | 'listItemInfo'
  | 'listsMutationResult'
  | 'commentInfo'
  | 'commentList'
  | 'commentReceipt'
  | 'trackChangeInfo'
  | 'trackChangeList'
  | 'trackChangeMutationReceipt'
  | 'tableMutationResult'
  | 'tableInfo'
  | 'tableCellList'
  | 'tablePropertiesInfo'
  | 'documentInfo'
  | 'receipt'
  | 'plain'
  | 'void'
  | 'diffSnapshot'
  | 'diffPayload'
  | 'diffApplyResult';

export const OUTPUT_FORMAT: Record<CliExposedOperationId, OutputFormat> = {
  get: 'plain',
  markdownToFragment: 'plain',
  find: 'queryResult',
  getNode: 'nodeInfo',
  getNodeById: 'nodeInfo',
  getText: 'plain',
  getMarkdown: 'plain',
  getHtml: 'plain',
  info: 'documentInfo',
  extract: 'plain',
  clearContent: 'receipt',
  insert: 'mutationReceipt',
  replace: 'mutationReceipt',
  delete: 'mutationReceipt',
  'blocks.list': 'plain',
  'blocks.delete': 'plain',
  'blocks.deleteRange': 'plain',
  formatRange: 'mutationReceipt',
  'format.apply': 'mutationReceipt',
  ...buildFormatInlineAliasRecord('mutationReceipt'),
  ...buildParagraphRecord('plain'),
  'styles.apply': 'receipt',
  'templates.apply': 'receipt',
  'create.paragraph': 'createResult',
  'create.heading': 'createResult',
  'create.tableOfContents': 'createResult',
  'lists.list': 'listResult',
  'lists.get': 'listItemInfo',
  'lists.insert': 'listsMutationResult',
  'lists.indent': 'listsMutationResult',
  'lists.outdent': 'listsMutationResult',
  'lists.create': 'listsMutationResult',
  'lists.attach': 'listsMutationResult',
  'lists.detach': 'listsMutationResult',
  'lists.join': 'listsMutationResult',
  'lists.canJoin': 'plain',
  'lists.separate': 'listsMutationResult',
  'lists.setLevel': 'listsMutationResult',
  'lists.setValue': 'listsMutationResult',
  'lists.continuePrevious': 'listsMutationResult',
  'lists.canContinuePrevious': 'plain',
  'lists.setLevelRestart': 'listsMutationResult',
  'lists.applyTemplate': 'listsMutationResult',
  'lists.applyPreset': 'listsMutationResult',
  'lists.captureTemplate': 'plain',
  'lists.setLevelNumbering': 'listsMutationResult',
  'lists.setLevelBullet': 'listsMutationResult',
  'lists.setLevelPictureBullet': 'listsMutationResult',
  'lists.setLevelAlignment': 'listsMutationResult',
  'lists.setLevelIndents': 'listsMutationResult',
  'lists.setLevelTrailingCharacter': 'listsMutationResult',
  'lists.setLevelMarkerFont': 'listsMutationResult',
  'lists.clearLevelOverrides': 'listsMutationResult',
  'lists.convertToText': 'listsMutationResult',
  'comments.create': 'commentReceipt',
  'comments.patch': 'commentReceipt',
  'comments.delete': 'commentReceipt',
  'comments.get': 'commentInfo',
  'comments.list': 'commentList',
  'trackChanges.list': 'trackChangeList',
  'trackChanges.get': 'trackChangeInfo',
  'trackChanges.decide': 'trackChangeMutationReceipt',
  'toc.list': 'plain',
  'toc.get': 'plain',
  'toc.configure': 'plain',
  'toc.update': 'plain',
  'toc.remove': 'plain',
  'toc.markEntry': 'plain',
  'toc.unmarkEntry': 'plain',
  'toc.listEntries': 'plain',
  'toc.getEntry': 'plain',
  'toc.editEntry': 'plain',
  'query.match': 'plain',
  'mutations.preview': 'plain',
  'mutations.apply': 'plain',
  'capabilities.get': 'plain',

  // Tables
  'create.table': 'createResult',
  'tables.convertFromText': 'tableMutationResult',
  'tables.delete': 'tableMutationResult',
  'tables.clearContents': 'tableMutationResult',
  'tables.move': 'tableMutationResult',
  'tables.split': 'tableMutationResult',
  'tables.convertToText': 'tableMutationResult',
  'tables.setLayout': 'tableMutationResult',
  'tables.insertRow': 'tableMutationResult',
  'tables.deleteRow': 'tableMutationResult',
  'tables.setRowHeight': 'tableMutationResult',
  'tables.distributeRows': 'tableMutationResult',
  'tables.setRowOptions': 'tableMutationResult',
  'tables.insertColumn': 'tableMutationResult',
  'tables.deleteColumn': 'tableMutationResult',
  'tables.setColumnWidth': 'tableMutationResult',
  'tables.distributeColumns': 'tableMutationResult',
  'tables.insertCell': 'tableMutationResult',
  'tables.deleteCell': 'tableMutationResult',
  'tables.mergeCells': 'tableMutationResult',
  'tables.unmergeCells': 'tableMutationResult',
  'tables.splitCell': 'tableMutationResult',
  'tables.setCellProperties': 'tableMutationResult',
  'tables.sort': 'tableMutationResult',
  'tables.setAltText': 'tableMutationResult',
  'tables.setStyle': 'tableMutationResult',
  'tables.clearStyle': 'tableMutationResult',
  'tables.setStyleOption': 'tableMutationResult',
  'tables.setBorder': 'tableMutationResult',
  'tables.clearBorder': 'tableMutationResult',
  'tables.applyBorderPreset': 'tableMutationResult',
  'tables.setShading': 'tableMutationResult',
  'tables.clearShading': 'tableMutationResult',
  'tables.setTablePadding': 'tableMutationResult',
  'tables.setCellPadding': 'tableMutationResult',
  'tables.setCellSpacing': 'tableMutationResult',
  'tables.clearCellSpacing': 'tableMutationResult',
  'tables.get': 'tableInfo',
  'tables.getCells': 'tableCellList',
  'tables.getProperties': 'tablePropertiesInfo',
  'tables.getStyles': 'plain',
  'tables.setDefaultStyle': 'plain',
  'tables.clearDefaultStyle': 'plain',
  'history.get': 'plain',
  'history.undo': 'plain',
  'history.redo': 'plain',

  // Images
  'create.image': 'createResult',
  'images.list': 'plain',
  'images.get': 'plain',
  'images.delete': 'plain',
  'images.move': 'plain',
  'images.convertToInline': 'plain',
  'images.convertToFloating': 'plain',
  'images.setSize': 'plain',
  'images.setWrapType': 'plain',
  'images.setWrapSide': 'plain',
  'images.setWrapDistances': 'plain',
  'images.setPosition': 'plain',
  'images.setAnchorOptions': 'plain',
  'images.setZOrder': 'plain',

  // Diff
  'diff.capture': 'diffSnapshot',
  'diff.compare': 'diffPayload',
  'diff.apply': 'diffApplyResult',

  // Every doc-api operation must declare an output format.
  // 'plain' falls back to the default Revision/verb pretty output (FORMAT_DISPATCH
  // has no entry for 'plain' so formatOutput returns null).
  'authorities.configure': 'plain',
  'authorities.entries.get': 'plain',
  'authorities.entries.insert': 'plain',
  'authorities.entries.list': 'plain',
  'authorities.entries.remove': 'plain',
  'authorities.entries.update': 'plain',
  'authorities.get': 'plain',
  'authorities.insert': 'plain',
  'authorities.list': 'plain',
  'authorities.rebuild': 'plain',
  'authorities.remove': 'plain',
  'bookmarks.get': 'plain',
  'bookmarks.insert': 'plain',
  'bookmarks.list': 'plain',
  'bookmarks.remove': 'plain',
  'bookmarks.rename': 'plain',
  'captions.configure': 'plain',
  'captions.get': 'plain',
  'captions.insert': 'plain',
  'captions.list': 'plain',
  'captions.remove': 'plain',
  'captions.update': 'plain',
  'citations.bibliography.configure': 'plain',
  'citations.bibliography.get': 'plain',
  'citations.bibliography.insert': 'plain',
  'citations.bibliography.rebuild': 'plain',
  'citations.bibliography.remove': 'plain',
  'citations.get': 'plain',
  'citations.insert': 'plain',
  'citations.list': 'plain',
  'citations.remove': 'plain',
  'citations.sources.get': 'plain',
  'citations.sources.insert': 'plain',
  'citations.sources.list': 'plain',
  'citations.sources.remove': 'plain',
  'citations.sources.update': 'plain',
  'citations.update': 'plain',
  'contentControls.appendContent': 'plain',
  'contentControls.checkbox.getState': 'plain',
  'contentControls.checkbox.setState': 'plain',
  'contentControls.checkbox.setSymbolPair': 'plain',
  'contentControls.checkbox.toggle': 'plain',
  'contentControls.choiceList.getItems': 'plain',
  'contentControls.choiceList.setItems': 'plain',
  'contentControls.choiceList.setSelected': 'plain',
  'contentControls.clearBinding': 'plain',
  'contentControls.clearContent': 'plain',
  'contentControls.copy': 'plain',
  'contentControls.date.clearValue': 'plain',
  'contentControls.date.setCalendar': 'plain',
  'contentControls.date.setDisplayFormat': 'plain',
  'contentControls.date.setDisplayLocale': 'plain',
  'contentControls.date.setStorageFormat': 'plain',
  'contentControls.date.setValue': 'plain',
  'contentControls.delete': 'plain',
  'contentControls.get': 'plain',
  'contentControls.getBinding': 'plain',
  'contentControls.getContent': 'plain',
  'contentControls.getParent': 'plain',
  'contentControls.getRawProperties': 'plain',
  'contentControls.group.ungroup': 'plain',
  'contentControls.group.wrap': 'plain',
  'contentControls.insertAfter': 'plain',
  'contentControls.insertBefore': 'plain',
  'contentControls.list': 'plain',
  'contentControls.listChildren': 'plain',
  'contentControls.listInRange': 'plain',
  'contentControls.move': 'plain',
  'contentControls.normalizeTagPayload': 'plain',
  'contentControls.normalizeWordCompatibility': 'plain',
  'contentControls.patch': 'plain',
  'contentControls.patchRawProperties': 'plain',
  'contentControls.prependContent': 'plain',
  'contentControls.repeatingSection.cloneItem': 'plain',
  'contentControls.repeatingSection.deleteItem': 'plain',
  'contentControls.repeatingSection.insertItemAfter': 'plain',
  'contentControls.repeatingSection.insertItemBefore': 'plain',
  'contentControls.repeatingSection.listItems': 'plain',
  'contentControls.repeatingSection.setAllowInsertDelete': 'plain',
  'contentControls.replaceContent': 'plain',
  'contentControls.selectByTag': 'plain',
  'contentControls.selectByTitle': 'plain',
  'contentControls.setBinding': 'plain',
  'contentControls.setLockMode': 'plain',
  'contentControls.setType': 'plain',
  'contentControls.text.clearValue': 'plain',
  'contentControls.text.setMultiline': 'plain',
  'contentControls.text.setValue': 'plain',
  'contentControls.unwrap': 'plain',
  'contentControls.validateWordCompatibility': 'plain',
  'contentControls.wrap': 'plain',
  'create.contentControl': 'plain',
  'create.sectionBreak': 'plain',
  'crossRefs.get': 'plain',
  'crossRefs.insert': 'plain',
  'crossRefs.list': 'plain',
  'crossRefs.rebuild': 'plain',
  'crossRefs.remove': 'plain',
  'customXml.parts.create': 'plain',
  'customXml.parts.get': 'plain',
  'customXml.parts.list': 'plain',
  'customXml.parts.patch': 'plain',
  'customXml.parts.remove': 'plain',
  'fields.get': 'plain',
  'fields.insert': 'plain',
  'fields.list': 'plain',
  'fields.rebuild': 'plain',
  'fields.remove': 'plain',
  'footnotes.configure': 'plain',
  'footnotes.get': 'plain',
  'footnotes.insert': 'plain',
  'footnotes.list': 'plain',
  'footnotes.remove': 'plain',
  'footnotes.update': 'plain',
  'format.paragraph.clearDirection': 'plain',
  'format.paragraph.setDirection': 'plain',
  'headerFooters.get': 'plain',
  'headerFooters.list': 'plain',
  'headerFooters.parts.create': 'plain',
  'headerFooters.parts.delete': 'plain',
  'headerFooters.parts.list': 'plain',
  'headerFooters.refs.clear': 'plain',
  'headerFooters.refs.set': 'plain',
  'headerFooters.refs.setLinkedToPrevious': 'plain',
  'headerFooters.resolve': 'plain',
  'hyperlinks.get': 'plain',
  'hyperlinks.insert': 'plain',
  'hyperlinks.list': 'plain',
  'hyperlinks.patch': 'plain',
  'hyperlinks.remove': 'plain',
  'hyperlinks.wrap': 'plain',
  'images.crop': 'plain',
  'images.flip': 'plain',
  'images.insertCaption': 'plain',
  'images.removeCaption': 'plain',
  'images.replaceSource': 'plain',
  'images.resetCrop': 'plain',
  'images.rotate': 'plain',
  'images.scale': 'plain',
  'images.setAltText': 'plain',
  'images.setDecorative': 'plain',
  'images.setHyperlink': 'plain',
  'images.setLockAspectRatio': 'plain',
  'images.setName': 'plain',
  'images.updateCaption': 'plain',
  'index.configure': 'plain',
  'index.entries.get': 'plain',
  'index.entries.insert': 'plain',
  'index.entries.list': 'plain',
  'index.entries.remove': 'plain',
  'index.entries.update': 'plain',
  'index.get': 'plain',
  'index.insert': 'plain',
  'index.list': 'plain',
  'index.rebuild': 'plain',
  'index.remove': 'plain',
  'lists.applyStyle': 'plain',
  'lists.delete': 'plain',
  'lists.getStyle': 'plain',
  'lists.merge': 'plain',
  'lists.restartAt': 'plain',
  'lists.setLevelLayout': 'plain',
  'lists.setLevelNumberStyle': 'plain',
  'lists.setLevelStart': 'plain',
  'lists.setLevelText': 'plain',
  'lists.setType': 'plain',
  'lists.split': 'plain',
  'metadata.attach': 'plain',
  'metadata.get': 'plain',
  'metadata.list': 'plain',
  'metadata.remove': 'plain',
  'metadata.resolve': 'plain',
  'metadata.update': 'plain',
  'permissionRanges.create': 'plain',
  'permissionRanges.get': 'plain',
  'permissionRanges.list': 'plain',
  'permissionRanges.remove': 'plain',
  'permissionRanges.updatePrincipal': 'plain',
  'protection.clearEditingRestriction': 'plain',
  'protection.get': 'plain',
  'protection.setEditingRestriction': 'plain',
  'ranges.resolve': 'plain',
  'sections.clearHeaderFooterRef': 'plain',
  'sections.clearPageBorders': 'plain',
  'sections.get': 'plain',
  'sections.list': 'plain',
  'sections.setBreakType': 'plain',
  'sections.setColumns': 'plain',
  'sections.setHeaderFooterMargins': 'plain',
  'sections.setHeaderFooterRef': 'plain',
  'sections.setLineNumbering': 'plain',
  'sections.setLinkToPrevious': 'plain',
  'sections.setOddEvenHeadersFooters': 'plain',
  'sections.setPageBorders': 'plain',
  'sections.setPageMargins': 'plain',
  'sections.setPageNumbering': 'plain',
  'sections.setPageSetup': 'plain',
  'sections.setSectionDirection': 'plain',
  'sections.setTitlePage': 'plain',
  'sections.setVerticalAlign': 'plain',
  'selection.current': 'plain',
  'tables.applyPreset': 'plain',
  'tables.applyStyle': 'plain',
  'tables.setBorders': 'plain',
  'tables.setCellText': 'plain',
  'tables.setTableOptions': 'plain',
};

// ---------------------------------------------------------------------------
// Response envelope key (single source of truth)
// ---------------------------------------------------------------------------

/**
 * Envelope key where the doc-api result payload lives in the CLI response.
 * This is the SINGLE SOURCE OF TRUTH — used by both orchestrators
 * and validateOperationResponseData().
 *
 * `null` means the result is spread across multiple top-level keys (e.g. info).
 */
export const RESPONSE_ENVELOPE_KEY: Record<CliExposedOperationId, string | null> = {
  get: 'result',
  markdownToFragment: 'result',
  find: 'result',
  getNode: 'node',
  getNodeById: 'node',
  getText: 'text',
  getMarkdown: 'markdown',
  getHtml: 'html',
  info: null,
  extract: null,
  clearContent: 'receipt',
  insert: null,
  replace: null,
  delete: null,
  'blocks.list': 'result',
  'blocks.delete': 'result',
  'blocks.deleteRange': 'result',
  formatRange: null,
  'format.apply': null,
  ...buildFormatInlineAliasRecord(null),
  ...buildParagraphRecord('result'),
  'styles.apply': 'receipt',
  'templates.apply': 'receipt',
  'create.paragraph': 'result',
  'create.heading': 'result',
  'create.tableOfContents': 'result',
  'lists.list': 'result',
  'lists.get': 'item',
  'lists.insert': 'result',
  'lists.indent': 'result',
  'lists.outdent': 'result',
  'lists.create': 'result',
  'lists.attach': 'result',
  'lists.detach': 'result',
  'lists.join': 'result',
  'lists.canJoin': 'result',
  'lists.separate': 'result',
  'lists.setLevel': 'result',
  'lists.setValue': 'result',
  'lists.continuePrevious': 'result',
  'lists.canContinuePrevious': 'result',
  'lists.setLevelRestart': 'result',
  'lists.applyTemplate': 'result',
  'lists.applyPreset': 'result',
  'lists.captureTemplate': 'result',
  'lists.setLevelNumbering': 'result',
  'lists.setLevelBullet': 'result',
  'lists.setLevelPictureBullet': 'result',
  'lists.setLevelAlignment': 'result',
  'lists.setLevelIndents': 'result',
  'lists.setLevelTrailingCharacter': 'result',
  'lists.setLevelMarkerFont': 'result',
  'lists.clearLevelOverrides': 'result',
  'lists.convertToText': 'result',
  'comments.create': 'receipt',
  'comments.patch': 'receipt',
  'comments.delete': 'receipt',
  'comments.get': 'comment',
  'comments.list': 'result',
  'trackChanges.list': 'result',
  'trackChanges.get': 'change',
  'trackChanges.decide': 'receipt',
  'toc.list': 'result',
  'toc.get': 'result',
  'toc.configure': 'result',
  'toc.update': 'result',
  'toc.remove': 'result',
  'toc.markEntry': 'result',
  'toc.unmarkEntry': 'result',
  'toc.listEntries': 'result',
  'toc.getEntry': 'result',
  'toc.editEntry': 'result',
  'query.match': 'result',
  'mutations.preview': 'result',
  'mutations.apply': 'result',
  'capabilities.get': 'capabilities',

  // Tables
  'create.table': 'result',
  'tables.convertFromText': 'result',
  'tables.delete': 'result',
  'tables.clearContents': 'result',
  'tables.move': 'result',
  'tables.split': 'result',
  'tables.convertToText': 'result',
  'tables.setLayout': 'result',
  'tables.insertRow': 'result',
  'tables.deleteRow': 'result',
  'tables.setRowHeight': 'result',
  'tables.distributeRows': 'result',
  'tables.setRowOptions': 'result',
  'tables.insertColumn': 'result',
  'tables.deleteColumn': 'result',
  'tables.setColumnWidth': 'result',
  'tables.distributeColumns': 'result',
  'tables.insertCell': 'result',
  'tables.deleteCell': 'result',
  'tables.mergeCells': 'result',
  'tables.unmergeCells': 'result',
  'tables.splitCell': 'result',
  'tables.setCellProperties': 'result',
  'tables.sort': 'result',
  'tables.setAltText': 'result',
  'tables.setStyle': 'result',
  'tables.clearStyle': 'result',
  'tables.setStyleOption': 'result',
  'tables.setBorder': 'result',
  'tables.clearBorder': 'result',
  'tables.applyBorderPreset': 'result',
  'tables.setShading': 'result',
  'tables.clearShading': 'result',
  'tables.setTablePadding': 'result',
  'tables.setCellPadding': 'result',
  'tables.setCellSpacing': 'result',
  'tables.clearCellSpacing': 'result',
  'tables.get': 'result',
  'tables.getCells': 'result',
  'tables.getProperties': 'result',
  'tables.getStyles': 'result',
  'tables.setDefaultStyle': 'result',
  'tables.clearDefaultStyle': 'result',
  'history.get': 'result',
  'history.undo': 'result',
  'history.redo': 'result',

  // Images
  'create.image': 'result',
  'images.list': 'result',
  'images.get': 'result',
  'images.delete': 'result',
  'images.move': 'result',
  'images.convertToInline': 'result',
  'images.convertToFloating': 'result',
  'images.setSize': 'result',
  'images.setWrapType': 'result',
  'images.setWrapSide': 'result',
  'images.setWrapDistances': 'result',
  'images.setPosition': 'result',
  'images.setAnchorOptions': 'result',
  'images.setZOrder': 'result',

  // Header/Footer
  'headerFooters.list': 'result',
  'headerFooters.get': 'result',
  'headerFooters.resolve': 'result',
  'headerFooters.refs.set': 'result',
  'headerFooters.refs.clear': 'result',
  'headerFooters.refs.setLinkedToPrevious': 'result',
  'headerFooters.parts.list': 'result',
  'headerFooters.parts.create': 'result',
  'headerFooters.parts.delete': 'result',

  // Diff
  'diff.capture': 'snapshot',
  'diff.compare': 'diff',
  'diff.apply': 'result',

  // Every doc-api operation must declare an envelope key so missing entries
  // can't degrade to `[undefined]: result` at runtime.
  'authorities.configure': 'result',
  'authorities.entries.get': 'result',
  'authorities.entries.insert': 'result',
  'authorities.entries.list': 'result',
  'authorities.entries.remove': 'result',
  'authorities.entries.update': 'result',
  'authorities.get': 'result',
  'authorities.insert': 'result',
  'authorities.list': 'result',
  'authorities.rebuild': 'result',
  'authorities.remove': 'result',
  'bookmarks.get': 'result',
  'bookmarks.insert': 'result',
  'bookmarks.list': 'result',
  'bookmarks.remove': 'result',
  'bookmarks.rename': 'result',
  'captions.configure': 'result',
  'captions.get': 'result',
  'captions.insert': 'result',
  'captions.list': 'result',
  'captions.remove': 'result',
  'captions.update': 'result',
  'citations.bibliography.configure': 'result',
  'citations.bibliography.get': 'result',
  'citations.bibliography.insert': 'result',
  'citations.bibliography.rebuild': 'result',
  'citations.bibliography.remove': 'result',
  'citations.get': 'result',
  'citations.insert': 'result',
  'citations.list': 'result',
  'citations.remove': 'result',
  'citations.sources.get': 'result',
  'citations.sources.insert': 'result',
  'citations.sources.list': 'result',
  'citations.sources.remove': 'result',
  'citations.sources.update': 'result',
  'citations.update': 'result',
  'contentControls.appendContent': 'result',
  'contentControls.checkbox.getState': 'result',
  'contentControls.checkbox.setState': 'result',
  'contentControls.checkbox.setSymbolPair': 'result',
  'contentControls.checkbox.toggle': 'result',
  'contentControls.choiceList.getItems': 'result',
  'contentControls.choiceList.setItems': 'result',
  'contentControls.choiceList.setSelected': 'result',
  'contentControls.clearBinding': 'result',
  'contentControls.clearContent': 'result',
  'contentControls.copy': 'result',
  'contentControls.date.clearValue': 'result',
  'contentControls.date.setCalendar': 'result',
  'contentControls.date.setDisplayFormat': 'result',
  'contentControls.date.setDisplayLocale': 'result',
  'contentControls.date.setStorageFormat': 'result',
  'contentControls.date.setValue': 'result',
  'contentControls.delete': 'result',
  'contentControls.get': 'result',
  'contentControls.getBinding': 'result',
  'contentControls.getContent': 'result',
  'contentControls.getParent': 'result',
  'contentControls.getRawProperties': 'result',
  'contentControls.group.ungroup': 'result',
  'contentControls.group.wrap': 'result',
  'contentControls.insertAfter': 'result',
  'contentControls.insertBefore': 'result',
  'contentControls.list': 'result',
  'contentControls.listChildren': 'result',
  'contentControls.listInRange': 'result',
  'contentControls.move': 'result',
  'contentControls.normalizeTagPayload': 'result',
  'contentControls.normalizeWordCompatibility': 'result',
  'contentControls.patch': 'result',
  'contentControls.patchRawProperties': 'result',
  'contentControls.prependContent': 'result',
  'contentControls.repeatingSection.cloneItem': 'result',
  'contentControls.repeatingSection.deleteItem': 'result',
  'contentControls.repeatingSection.insertItemAfter': 'result',
  'contentControls.repeatingSection.insertItemBefore': 'result',
  'contentControls.repeatingSection.listItems': 'result',
  'contentControls.repeatingSection.setAllowInsertDelete': 'result',
  'contentControls.replaceContent': 'result',
  'contentControls.selectByTag': 'result',
  'contentControls.selectByTitle': 'result',
  'contentControls.setBinding': 'result',
  'contentControls.setLockMode': 'result',
  'contentControls.setType': 'result',
  'contentControls.text.clearValue': 'result',
  'contentControls.text.setMultiline': 'result',
  'contentControls.text.setValue': 'result',
  'contentControls.unwrap': 'result',
  'contentControls.validateWordCompatibility': 'result',
  'contentControls.wrap': 'result',
  'create.contentControl': 'result',
  'create.sectionBreak': 'result',
  'crossRefs.get': 'result',
  'crossRefs.insert': 'result',
  'crossRefs.list': 'result',
  'crossRefs.rebuild': 'result',
  'crossRefs.remove': 'result',
  'customXml.parts.create': 'result',
  'customXml.parts.get': 'result',
  'customXml.parts.list': 'result',
  'customXml.parts.patch': 'result',
  'customXml.parts.remove': 'result',
  'fields.get': 'result',
  'fields.insert': 'result',
  'fields.list': 'result',
  'fields.rebuild': 'result',
  'fields.remove': 'result',
  'footnotes.configure': 'result',
  'footnotes.get': 'result',
  'footnotes.insert': 'result',
  'footnotes.list': 'result',
  'footnotes.remove': 'result',
  'footnotes.update': 'result',
  'format.paragraph.clearDirection': 'result',
  'format.paragraph.setDirection': 'result',
  'hyperlinks.get': 'result',
  'hyperlinks.insert': 'result',
  'hyperlinks.list': 'result',
  'hyperlinks.patch': 'result',
  'hyperlinks.remove': 'result',
  'hyperlinks.wrap': 'result',
  'images.crop': 'result',
  'images.flip': 'result',
  'images.insertCaption': 'result',
  'images.removeCaption': 'result',
  'images.replaceSource': 'result',
  'images.resetCrop': 'result',
  'images.rotate': 'result',
  'images.scale': 'result',
  'images.setAltText': 'result',
  'images.setDecorative': 'result',
  'images.setHyperlink': 'result',
  'images.setLockAspectRatio': 'result',
  'images.setName': 'result',
  'images.updateCaption': 'result',
  'index.configure': 'result',
  'index.entries.get': 'result',
  'index.entries.insert': 'result',
  'index.entries.list': 'result',
  'index.entries.remove': 'result',
  'index.entries.update': 'result',
  'index.get': 'result',
  'index.insert': 'result',
  'index.list': 'result',
  'index.rebuild': 'result',
  'index.remove': 'result',
  'lists.applyStyle': 'result',
  'lists.delete': 'result',
  'lists.getStyle': 'result',
  'lists.merge': 'result',
  'lists.restartAt': 'result',
  'lists.setLevelLayout': 'result',
  'lists.setLevelNumberStyle': 'result',
  'lists.setLevelStart': 'result',
  'lists.setLevelText': 'result',
  'lists.setType': 'result',
  'lists.split': 'result',
  'metadata.attach': 'result',
  'metadata.get': 'result',
  'metadata.list': 'result',
  'metadata.remove': 'result',
  'metadata.resolve': 'result',
  'metadata.update': 'result',
  'permissionRanges.create': 'result',
  'permissionRanges.get': 'result',
  'permissionRanges.list': 'result',
  'permissionRanges.remove': 'result',
  'permissionRanges.updatePrincipal': 'result',
  'protection.clearEditingRestriction': 'result',
  'protection.get': 'result',
  'protection.setEditingRestriction': 'result',
  'ranges.resolve': 'result',
  'sections.clearHeaderFooterRef': 'result',
  'sections.clearPageBorders': 'result',
  'sections.get': 'result',
  'sections.list': 'result',
  'sections.setBreakType': 'result',
  'sections.setColumns': 'result',
  'sections.setHeaderFooterMargins': 'result',
  'sections.setHeaderFooterRef': 'result',
  'sections.setLineNumbering': 'result',
  'sections.setLinkToPrevious': 'result',
  'sections.setOddEvenHeadersFooters': 'result',
  'sections.setPageBorders': 'result',
  'sections.setPageMargins': 'result',
  'sections.setPageNumbering': 'result',
  'sections.setPageSetup': 'result',
  'sections.setSectionDirection': 'result',
  'sections.setTitlePage': 'result',
  'sections.setVerticalAlign': 'result',
  'selection.current': 'result',
  'tables.applyPreset': 'result',
  'tables.applyStyle': 'result',
  'tables.setBorders': 'result',
  'tables.setCellText': 'result',
  'tables.setTableOptions': 'result',
};

// ---------------------------------------------------------------------------
// Response validation key (fallback for null envelope keys)
// ---------------------------------------------------------------------------

/**
 * When RESPONSE_ENVELOPE_KEY is `null` (result is spread across top-level keys),
 * this map specifies which key to validate against the doc-api output schema.
 *
 * Operations without an entry here AND a null envelope key skip schema validation
 * (e.g. `info`, which splits output across counts/outline/capabilities).
 */
export const RESPONSE_VALIDATION_KEY: Partial<Record<CliExposedOperationId, string>> = {
  insert: 'receipt',
  replace: 'receipt',
  delete: 'receipt',
  formatRange: 'receipt',
  'format.apply': 'receipt',
  ...buildFormatInlineAliasRecord('receipt'),
};

// ---------------------------------------------------------------------------
// Operation family (determines error-mapping rules)
// ---------------------------------------------------------------------------

/**
 * Operation family — determines which error-mapping rules apply.
 * Explicit Record for compile-time completeness (no string-prefix heuristics).
 */
export type OperationFamily =
  | 'trackChanges'
  | 'comments'
  | 'lists'
  | 'tables'
  | 'images'
  | 'toc'
  | 'textMutation'
  | 'create'
  | 'blocks'
  | 'query'
  | 'diff'
  | 'templates'
  | 'general';

export const OPERATION_FAMILY: Record<CliExposedOperationId, OperationFamily> = {
  get: 'query',
  markdownToFragment: 'general',
  find: 'query',
  getNode: 'query',
  getNodeById: 'query',
  getText: 'query',
  getMarkdown: 'query',
  getHtml: 'query',
  info: 'general',
  extract: 'general',
  clearContent: 'general',
  insert: 'textMutation',
  replace: 'textMutation',
  delete: 'textMutation',
  'blocks.list': 'blocks',
  'blocks.delete': 'blocks',
  'blocks.deleteRange': 'blocks',
  formatRange: 'textMutation',
  'format.apply': 'textMutation',
  ...buildFormatInlineAliasRecord('textMutation'),
  ...buildParagraphRecord('textMutation'),
  'styles.apply': 'general',
  'templates.apply': 'templates',
  'create.paragraph': 'create',
  'create.heading': 'create',
  'create.tableOfContents': 'create',
  'lists.list': 'lists',
  'lists.get': 'lists',
  'lists.insert': 'lists',
  'lists.indent': 'lists',
  'lists.outdent': 'lists',
  'lists.create': 'lists',
  'lists.attach': 'lists',
  'lists.detach': 'lists',
  'lists.join': 'lists',
  'lists.canJoin': 'lists',
  'lists.separate': 'lists',
  'lists.setLevel': 'lists',
  'lists.setValue': 'lists',
  'lists.continuePrevious': 'lists',
  'lists.canContinuePrevious': 'lists',
  'lists.setLevelRestart': 'lists',
  'lists.applyTemplate': 'lists',
  'lists.applyPreset': 'lists',
  'lists.captureTemplate': 'lists',
  'lists.setLevelNumbering': 'lists',
  'lists.setLevelBullet': 'lists',
  'lists.setLevelPictureBullet': 'lists',
  'lists.setLevelAlignment': 'lists',
  'lists.setLevelIndents': 'lists',
  'lists.setLevelTrailingCharacter': 'lists',
  'lists.setLevelMarkerFont': 'lists',
  'lists.clearLevelOverrides': 'lists',
  'lists.convertToText': 'lists',
  'comments.create': 'comments',
  'comments.patch': 'comments',
  'comments.delete': 'comments',
  'comments.get': 'comments',
  'comments.list': 'comments',
  'trackChanges.list': 'trackChanges',
  'trackChanges.get': 'trackChanges',
  'trackChanges.decide': 'trackChanges',
  'toc.list': 'query',
  'toc.get': 'query',
  'toc.configure': 'toc',
  'toc.update': 'toc',
  'toc.remove': 'toc',
  'toc.markEntry': 'toc',
  'toc.unmarkEntry': 'toc',
  'toc.listEntries': 'query',
  'toc.getEntry': 'query',
  'toc.editEntry': 'toc',
  'query.match': 'query',
  'mutations.preview': 'general',
  'mutations.apply': 'general',
  'capabilities.get': 'general',

  // Tables
  'create.table': 'tables',
  'tables.convertFromText': 'tables',
  'tables.delete': 'tables',
  'tables.clearContents': 'tables',
  'tables.move': 'tables',
  'tables.split': 'tables',
  'tables.convertToText': 'tables',
  'tables.setLayout': 'tables',
  'tables.insertRow': 'tables',
  'tables.deleteRow': 'tables',
  'tables.setRowHeight': 'tables',
  'tables.distributeRows': 'tables',
  'tables.setRowOptions': 'tables',
  'tables.insertColumn': 'tables',
  'tables.deleteColumn': 'tables',
  'tables.setColumnWidth': 'tables',
  'tables.distributeColumns': 'tables',
  'tables.insertCell': 'tables',
  'tables.deleteCell': 'tables',
  'tables.mergeCells': 'tables',
  'tables.unmergeCells': 'tables',
  'tables.splitCell': 'tables',
  'tables.setCellProperties': 'tables',
  'tables.sort': 'tables',
  'tables.setAltText': 'tables',
  'tables.setStyle': 'tables',
  'tables.clearStyle': 'tables',
  'tables.setStyleOption': 'tables',
  'tables.setBorder': 'tables',
  'tables.clearBorder': 'tables',
  'tables.applyBorderPreset': 'tables',
  'tables.setShading': 'tables',
  'tables.clearShading': 'tables',
  'tables.setTablePadding': 'tables',
  'tables.setCellPadding': 'tables',
  'tables.setCellSpacing': 'tables',
  'tables.clearCellSpacing': 'tables',
  'tables.get': 'tables',
  'tables.getCells': 'tables',
  'tables.getProperties': 'tables',
  'tables.getStyles': 'tables',
  'tables.setDefaultStyle': 'tables',
  'tables.clearDefaultStyle': 'tables',
  'history.get': 'query',
  'history.undo': 'general',
  'history.redo': 'general',

  // Images
  'create.image': 'images',
  'images.list': 'images',
  'images.get': 'images',
  'images.delete': 'images',
  'images.move': 'images',
  'images.convertToInline': 'images',
  'images.convertToFloating': 'images',
  'images.setSize': 'images',
  'images.setWrapType': 'images',
  'images.setWrapSide': 'images',
  'images.setWrapDistances': 'images',
  'images.setPosition': 'images',
  'images.setAnchorOptions': 'images',
  'images.setZOrder': 'images',

  // Diff
  'diff.capture': 'diff',
  'diff.compare': 'diff',
  'diff.apply': 'diff',

  // Every doc-api operation must declare a family.
  // 'general' mirrors the existing runtime fallback in error-mapping.ts.
  'authorities.configure': 'general',
  'authorities.entries.get': 'general',
  'authorities.entries.insert': 'general',
  'authorities.entries.list': 'general',
  'authorities.entries.remove': 'general',
  'authorities.entries.update': 'general',
  'authorities.get': 'general',
  'authorities.insert': 'general',
  'authorities.list': 'general',
  'authorities.rebuild': 'general',
  'authorities.remove': 'general',
  'bookmarks.get': 'general',
  'bookmarks.insert': 'general',
  'bookmarks.list': 'general',
  'bookmarks.remove': 'general',
  'bookmarks.rename': 'general',
  'captions.configure': 'general',
  'captions.get': 'general',
  'captions.insert': 'general',
  'captions.list': 'general',
  'captions.remove': 'general',
  'captions.update': 'general',
  'citations.bibliography.configure': 'general',
  'citations.bibliography.get': 'general',
  'citations.bibliography.insert': 'general',
  'citations.bibliography.rebuild': 'general',
  'citations.bibliography.remove': 'general',
  'citations.get': 'general',
  'citations.insert': 'general',
  'citations.list': 'general',
  'citations.remove': 'general',
  'citations.sources.get': 'general',
  'citations.sources.insert': 'general',
  'citations.sources.list': 'general',
  'citations.sources.remove': 'general',
  'citations.sources.update': 'general',
  'citations.update': 'general',
  'contentControls.appendContent': 'general',
  'contentControls.checkbox.getState': 'general',
  'contentControls.checkbox.setState': 'general',
  'contentControls.checkbox.setSymbolPair': 'general',
  'contentControls.checkbox.toggle': 'general',
  'contentControls.choiceList.getItems': 'general',
  'contentControls.choiceList.setItems': 'general',
  'contentControls.choiceList.setSelected': 'general',
  'contentControls.clearBinding': 'general',
  'contentControls.clearContent': 'general',
  'contentControls.copy': 'general',
  'contentControls.date.clearValue': 'general',
  'contentControls.date.setCalendar': 'general',
  'contentControls.date.setDisplayFormat': 'general',
  'contentControls.date.setDisplayLocale': 'general',
  'contentControls.date.setStorageFormat': 'general',
  'contentControls.date.setValue': 'general',
  'contentControls.delete': 'general',
  'contentControls.get': 'general',
  'contentControls.getBinding': 'general',
  'contentControls.getContent': 'general',
  'contentControls.getParent': 'general',
  'contentControls.getRawProperties': 'general',
  'contentControls.group.ungroup': 'general',
  'contentControls.group.wrap': 'general',
  'contentControls.insertAfter': 'general',
  'contentControls.insertBefore': 'general',
  'contentControls.list': 'general',
  'contentControls.listChildren': 'general',
  'contentControls.listInRange': 'general',
  'contentControls.move': 'general',
  'contentControls.normalizeTagPayload': 'general',
  'contentControls.normalizeWordCompatibility': 'general',
  'contentControls.patch': 'general',
  'contentControls.patchRawProperties': 'general',
  'contentControls.prependContent': 'general',
  'contentControls.repeatingSection.cloneItem': 'general',
  'contentControls.repeatingSection.deleteItem': 'general',
  'contentControls.repeatingSection.insertItemAfter': 'general',
  'contentControls.repeatingSection.insertItemBefore': 'general',
  'contentControls.repeatingSection.listItems': 'general',
  'contentControls.repeatingSection.setAllowInsertDelete': 'general',
  'contentControls.replaceContent': 'general',
  'contentControls.selectByTag': 'general',
  'contentControls.selectByTitle': 'general',
  'contentControls.setBinding': 'general',
  'contentControls.setLockMode': 'general',
  'contentControls.setType': 'general',
  'contentControls.text.clearValue': 'general',
  'contentControls.text.setMultiline': 'general',
  'contentControls.text.setValue': 'general',
  'contentControls.unwrap': 'general',
  'contentControls.validateWordCompatibility': 'general',
  'contentControls.wrap': 'general',
  'create.contentControl': 'general',
  'create.sectionBreak': 'general',
  'crossRefs.get': 'general',
  'crossRefs.insert': 'general',
  'crossRefs.list': 'general',
  'crossRefs.rebuild': 'general',
  'crossRefs.remove': 'general',
  'customXml.parts.create': 'general',
  'customXml.parts.get': 'general',
  'customXml.parts.list': 'general',
  'customXml.parts.patch': 'general',
  'customXml.parts.remove': 'general',
  'fields.get': 'general',
  'fields.insert': 'general',
  'fields.list': 'general',
  'fields.rebuild': 'general',
  'fields.remove': 'general',
  'footnotes.configure': 'general',
  'footnotes.get': 'general',
  'footnotes.insert': 'general',
  'footnotes.list': 'general',
  'footnotes.remove': 'general',
  'footnotes.update': 'general',
  'format.paragraph.clearDirection': 'general',
  'format.paragraph.setDirection': 'general',
  'headerFooters.get': 'general',
  'headerFooters.list': 'general',
  'headerFooters.parts.create': 'general',
  'headerFooters.parts.delete': 'general',
  'headerFooters.parts.list': 'general',
  'headerFooters.refs.clear': 'general',
  'headerFooters.refs.set': 'general',
  'headerFooters.refs.setLinkedToPrevious': 'general',
  'headerFooters.resolve': 'general',
  'hyperlinks.get': 'general',
  'hyperlinks.insert': 'general',
  'hyperlinks.list': 'general',
  'hyperlinks.patch': 'general',
  'hyperlinks.remove': 'general',
  'hyperlinks.wrap': 'general',
  'images.crop': 'general',
  'images.flip': 'general',
  'images.insertCaption': 'general',
  'images.removeCaption': 'general',
  'images.replaceSource': 'general',
  'images.resetCrop': 'general',
  'images.rotate': 'general',
  'images.scale': 'general',
  'images.setAltText': 'general',
  'images.setDecorative': 'general',
  'images.setHyperlink': 'general',
  'images.setLockAspectRatio': 'general',
  'images.setName': 'general',
  'images.updateCaption': 'general',
  'index.configure': 'general',
  'index.entries.get': 'general',
  'index.entries.insert': 'general',
  'index.entries.list': 'general',
  'index.entries.remove': 'general',
  'index.entries.update': 'general',
  'index.get': 'general',
  'index.insert': 'general',
  'index.list': 'general',
  'index.rebuild': 'general',
  'index.remove': 'general',
  'lists.applyStyle': 'general',
  'lists.delete': 'general',
  'lists.getStyle': 'general',
  'lists.merge': 'general',
  'lists.restartAt': 'general',
  'lists.setLevelLayout': 'general',
  'lists.setLevelNumberStyle': 'general',
  'lists.setLevelStart': 'general',
  'lists.setLevelText': 'general',
  'lists.setType': 'general',
  'lists.split': 'general',
  'metadata.attach': 'general',
  'metadata.get': 'general',
  'metadata.list': 'general',
  'metadata.remove': 'general',
  'metadata.resolve': 'general',
  'metadata.update': 'general',
  'permissionRanges.create': 'general',
  'permissionRanges.get': 'general',
  'permissionRanges.list': 'general',
  'permissionRanges.remove': 'general',
  'permissionRanges.updatePrincipal': 'general',
  'protection.clearEditingRestriction': 'general',
  'protection.get': 'general',
  'protection.setEditingRestriction': 'general',
  'ranges.resolve': 'general',
  'sections.clearHeaderFooterRef': 'general',
  'sections.clearPageBorders': 'general',
  'sections.get': 'general',
  'sections.list': 'general',
  'sections.setBreakType': 'general',
  'sections.setColumns': 'general',
  'sections.setHeaderFooterMargins': 'general',
  'sections.setHeaderFooterRef': 'general',
  'sections.setLineNumbering': 'general',
  'sections.setLinkToPrevious': 'general',
  'sections.setOddEvenHeadersFooters': 'general',
  'sections.setPageBorders': 'general',
  'sections.setPageMargins': 'general',
  'sections.setPageNumbering': 'general',
  'sections.setPageSetup': 'general',
  'sections.setSectionDirection': 'general',
  'sections.setTitlePage': 'general',
  'sections.setVerticalAlign': 'general',
  'selection.current': 'general',
  'tables.applyPreset': 'general',
  'tables.applyStyle': 'general',
  'tables.setBorders': 'general',
  'tables.setCellText': 'general',
  'tables.setTableOptions': 'general',
};
