/**
 * Integration tests for ooxml-encryption using a real encrypted .docx fixture.
 *
 * The fixture at `fixtures/encrypted-hello.docx` is a CFB container created with
 * Agile Encryption (AES-256-CBC, SHA-512, spinCount=100000) and password "test123".
 * It contains a minimal .docx ZIP with a "Hello, encrypted world!" paragraph.
 *
 * Generated by: fixtures/create-encrypted-fixture.mjs
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { decryptDocxIfNeeded } from './decrypt-docx.js';
import { DocxEncryptionError, DocxEncryptionErrorCode } from './errors.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = resolve(__dirname, 'fixtures', 'encrypted-hello.docx');

const CORRECT_PASSWORD = 'test123';

function loadFixture(): Uint8Array {
  return new Uint8Array(readFileSync(FIXTURE_PATH));
}

/** ZIP files start with PK\x03\x04 */
function isZip(data: Uint8Array): boolean {
  return data.length >= 4 && data[0] === 0x50 && data[1] === 0x4b && data[2] === 0x03 && data[3] === 0x04;
}

describe('decryptDocxIfNeeded — encrypted fixture integration', () => {
  it('decrypts an encrypted .docx with the correct password', async () => {
    const encrypted = loadFixture();

    const result = await decryptDocxIfNeeded(encrypted, { password: CORRECT_PASSWORD });

    expect(result.wasEncrypted).toBe(true);
    expect(result.data).toBeInstanceOf(Uint8Array);
    expect(result.data.length).toBeGreaterThan(0);

    // The decrypted output must be a valid ZIP
    expect(isZip(result.data)).toBe(true);
  }, 30_000); // key derivation with spinCount=100000 can be slow

  it('decrypted output is a valid ZIP that can be parsed', async () => {
    const encrypted = loadFixture();
    const result = await decryptDocxIfNeeded(encrypted, { password: CORRECT_PASSWORD });

    // Use JSZip to verify the ZIP is structurally valid
    const JSZip = (await import('jszip')).default;
    const zip = await JSZip.loadAsync(result.data);
    const fileNames = Object.keys(zip.files);

    // Must contain the core .docx parts we put in
    expect(fileNames).toContain('[Content_Types].xml');
    expect(fileNames).toContain('word/document.xml');
  }, 30_000);

  it('decrypted document.xml contains expected content', async () => {
    const encrypted = loadFixture();
    const result = await decryptDocxIfNeeded(encrypted, { password: CORRECT_PASSWORD });

    const JSZip = (await import('jszip')).default;
    const zip = await JSZip.loadAsync(result.data);
    const documentXml = await zip.file('word/document.xml')!.async('text');

    expect(documentXml).toContain('Hello, encrypted world!');
  }, 30_000);

  it('throws PASSWORD_REQUIRED when no password is provided', async () => {
    const encrypted = loadFixture();

    try {
      await decryptDocxIfNeeded(encrypted);
      expect.fail('Expected a DocxEncryptionError');
    } catch (err) {
      expect(err).toBeInstanceOf(DocxEncryptionError);
      expect((err as DocxEncryptionError).code).toBe(DocxEncryptionErrorCode.PASSWORD_REQUIRED);
    }
  });

  it('throws PASSWORD_REQUIRED when password is undefined', async () => {
    const encrypted = loadFixture();

    try {
      await decryptDocxIfNeeded(encrypted, { password: undefined });
      expect.fail('Expected a DocxEncryptionError');
    } catch (err) {
      expect(err).toBeInstanceOf(DocxEncryptionError);
      expect((err as DocxEncryptionError).code).toBe(DocxEncryptionErrorCode.PASSWORD_REQUIRED);
    }
  });

  it('throws PASSWORD_INVALID for the wrong password', async () => {
    const encrypted = loadFixture();

    try {
      await decryptDocxIfNeeded(encrypted, { password: 'wrong-password' });
      expect.fail('Expected a DocxEncryptionError');
    } catch (err) {
      expect(err).toBeInstanceOf(DocxEncryptionError);
      expect((err as DocxEncryptionError).code).toBe(DocxEncryptionErrorCode.PASSWORD_INVALID);
    }
  }, 30_000); // key derivation still happens before the password check fails

  it('the fixture file starts with CFB magic bytes', () => {
    const encrypted = loadFixture();

    // CFB magic: D0 CF 11 E0 A1 B1 1A E1
    expect(encrypted[0]).toBe(0xd0);
    expect(encrypted[1]).toBe(0xcf);
    expect(encrypted[2]).toBe(0x11);
    expect(encrypted[3]).toBe(0xe0);
    expect(encrypted[4]).toBe(0xa1);
    expect(encrypted[5]).toBe(0xb1);
    expect(encrypted[6]).toBe(0x1a);
    expect(encrypted[7]).toBe(0xe1);
  });

  it('accepts ArrayBuffer input', async () => {
    const encrypted = loadFixture();
    const arrayBuffer = encrypted.buffer.slice(encrypted.byteOffset, encrypted.byteOffset + encrypted.byteLength);

    const result = await decryptDocxIfNeeded(arrayBuffer, { password: CORRECT_PASSWORD });

    expect(result.wasEncrypted).toBe(true);
    expect(isZip(result.data)).toBe(true);
  }, 30_000);
});
