#!/usr/bin/env python3
"""
Generate a DOCX file with comments using python-docx for testing SuperDoc.

This script creates test DOCX files to help diagnose GitHub issue #752:
Comments created via python-docx are not visible in SuperDoc, though they
display correctly in MS Word and Google Docs.

Setup:
    python3 -m venv .venv
    source .venv/bin/activate  # On Windows: .venv\\Scripts\\activate
    pip install python-docx lxml

Usage:
    python generate_python_docx_comment.py

Output:
    python_docx_comment_test.docx - Test file with a comment
"""

import sys

# Check for dependencies before importing
try:
    from docx import Document
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from lxml import etree
except ImportError as e:
    print("Error: Missing required dependencies.")
    print()
    print("Please install them using:")
    print("    python3 -m venv .venv")
    print("    source .venv/bin/activate  # On Windows: .venv\\Scripts\\activate")
    print("    pip install python-docx lxml")
    print()
    print(f"Details: {e}")
    sys.exit(1)

import os
import re
import zipfile
from datetime import datetime


def create_comment_test_doc():
    """
    Create a DOCX with a comment for testing SuperDoc.

    Returns:
        tuple: (Document, bytes) - The document and comments XML
    """
    doc = Document()

    # Add a title
    doc.add_heading("Python-docx Comment Test", level=1)

    # Add explanation paragraph
    doc.add_paragraph(
        "This document was generated by python-docx to test comment handling in SuperDoc. "
        "See GitHub issue #752 for context."
    )

    # Add paragraph with commented text
    para = doc.add_paragraph()
    para.add_run("Normal text before. ")
    commented_run = para.add_run("THIS TEXT HAS A COMMENT")
    para.add_run(" Normal text after.")

    # Add comment markers to the document XML
    run_elem = commented_run._element

    # Create and insert commentRangeStart before the run
    comment_start = OxmlElement("w:commentRangeStart")
    comment_start.set(qn("w:id"), "0")
    run_elem.addprevious(comment_start)

    # Create and insert commentRangeEnd after the run
    comment_end = OxmlElement("w:commentRangeEnd")
    comment_end.set(qn("w:id"), "0")
    run_elem.addnext(comment_end)

    # Create commentReference in a new run after commentRangeEnd
    ref_run = OxmlElement("w:r")
    comment_ref = OxmlElement("w:commentReference")
    comment_ref.set(qn("w:id"), "0")
    ref_run.append(comment_ref)
    comment_end.addnext(ref_run)

    # Create the comments.xml content
    comments_xml = create_comments_xml([
        {
            "id": "0",
            "author": "Python-docx Script",
            "initials": "PS",
            "date": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
            "text": "This is a comment created by python-docx for testing SuperDoc",
        }
    ])

    return doc, comments_xml


def create_comments_xml(comments):
    """
    Create the comments.xml content for a DOCX file.

    Args:
        comments: List of dicts with id, author, initials, date, text

    Returns:
        bytes: The XML content
    """
    W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
    W14_NS = "http://schemas.microsoft.com/office/word/2010/wordml"

    nsmap = {
        "w": W_NS,
        "w14": W14_NS,
    }

    comments_root = etree.Element(f"{{{W_NS}}}comments", nsmap=nsmap)

    for comment_data in comments:
        # Create the comment element
        comment = etree.SubElement(comments_root, f"{{{W_NS}}}comment")
        comment.set(f"{{{W_NS}}}id", comment_data["id"])
        comment.set(f"{{{W_NS}}}author", comment_data["author"])
        comment.set(f"{{{W_NS}}}initials", comment_data["initials"])
        comment.set(f"{{{W_NS}}}date", comment_data["date"])

        # Add paragraph inside comment
        comment_para = etree.SubElement(comment, f"{{{W_NS}}}p")

        # Add w14:paraId attribute (SuperDoc uses this for comment identification)
        para_id = f"{int(comment_data['id']) + 1:08X}"
        comment_para.set(f"{{{W14_NS}}}paraId", para_id)

        # Add run with text
        comment_run = etree.SubElement(comment_para, f"{{{W_NS}}}r")
        comment_text = etree.SubElement(comment_run, f"{{{W_NS}}}t")
        comment_text.text = comment_data["text"]

    return etree.tostring(
        comments_root,
        xml_declaration=True,
        encoding="UTF-8",
        standalone=True,
    )


def add_comments_to_docx(docx_path, comments_xml):
    """
    Add comments.xml to an existing DOCX file.

    DOCX files are ZIP archives, so we modify the archive to:
    1. Add word/comments.xml
    2. Update [Content_Types].xml to include the comments content type
    3. Update word/_rels/document.xml.rels to include the comments relationship

    Args:
        docx_path: Path to the DOCX file
        comments_xml: The comments XML content as bytes
    """
    temp_path = docx_path + ".temp"
    os.rename(docx_path, temp_path)

    with zipfile.ZipFile(temp_path, "r") as zip_read:
        with zipfile.ZipFile(docx_path, "w", zipfile.ZIP_DEFLATED) as zip_write:
            for item in zip_read.namelist():
                content = zip_read.read(item)

                if item == "[Content_Types].xml":
                    content = add_comments_content_type(content)
                elif item == "word/_rels/document.xml.rels":
                    content = add_comments_relationship(content)

                zip_write.writestr(item, content)

            # Add the comments.xml file
            zip_write.writestr("word/comments.xml", comments_xml)

    os.remove(temp_path)


def add_comments_content_type(content):
    """Add the comments content type to [Content_Types].xml."""
    content_str = content.decode("utf-8")
    if "comments+xml" not in content_str:
        content_str = content_str.replace(
            "</Types>",
            '  <Override PartName="/word/comments.xml" '
            'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"/>\n'
            "</Types>",
        )
    return content_str.encode("utf-8")


def add_comments_relationship(content):
    """Add the comments relationship to word/_rels/document.xml.rels."""
    content_str = content.decode("utf-8")
    if "comments.xml" not in content_str:
        # Find the next available rId
        rids = re.findall(r'Id="rId(\d+)"', content_str)
        next_rid = max([int(r) for r in rids]) + 1 if rids else 1
        content_str = content_str.replace(
            "</Relationships>",
            f'  <Relationship Id="rId{next_rid}" '
            f'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" '
            f'Target="comments.xml"/>\n'
            "</Relationships>",
        )
    return content_str.encode("utf-8")


def main():
    """Generate the test DOCX file."""
    print("Generating DOCX with comments using python-docx...")
    print()

    output_file = "python_docx_comment_test.docx"

    try:
        # Create document with comment markers
        doc, comments_xml = create_comment_test_doc()

        # Save the document
        doc.save(output_file)

        # Add comments.xml to the saved document
        add_comments_to_docx(output_file, comments_xml)

        print(f"Created: {output_file}")
        print()
        print("The document contains:")
        print("  - A heading: 'Python-docx Comment Test'")
        print("  - A paragraph explaining the test")
        print("  - A paragraph with 'THIS TEXT HAS A COMMENT' that has a comment attached")
        print()
        print("Test this file by:")
        print("  1. Opening in MS Word or Google Docs - comment should be visible")
        print("  2. Opening in SuperDoc - comment may not be visible (issue #752)")
        print()
        print("To debug, compare the XML structure:")
        print()
        print("  # View this file's comments.xml:")
        print(f"  unzip -p {output_file} word/comments.xml | xmllint --format -")
        print()
        print("  # View comment markers in document.xml:")
        print(f"  unzip -p {output_file} word/document.xml | xmllint --format - | grep -A5 -B5 comment")
        print()
        print("  # Compare with a working test fixture:")
        print("  unzip -p packages/super-editor/src/editors/v1/tests/data/basic-comment.docx word/comments.xml | xmllint --format -")

    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
