# Auto-generated by generate-intent-tools.mjs — do not edit

from typing import Any, Callable, Dict

from ..errors import SuperDocError


def dispatch_intent_tool(
    tool_name: str,
    args: Dict[str, Any],
    execute: Callable[[str, Dict[str, Any]], Any],
) -> Any:
    if tool_name == 'superdoc_get_content':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'text':
            return execute('doc.getText', rest)
        elif action == 'markdown':
            return execute('doc.getMarkdown', rest)
        elif action == 'html':
            return execute('doc.getHtml', rest)
        elif action == 'info':
            return execute('doc.info', rest)
        elif action == 'extract':
            return execute('doc.extract', rest)
        elif action == 'blocks':
            return execute('doc.blocks.list', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_get_content: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_get_content', 'action': action})
    elif tool_name == 'superdoc_edit':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'insert':
            return execute('doc.insert', rest)
        elif action == 'replace':
            return execute('doc.replace', rest)
        elif action == 'delete':
            return execute('doc.delete', rest)
        elif action == 'undo':
            return execute('doc.history.undo', rest)
        elif action == 'redo':
            return execute('doc.history.redo', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_edit: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_edit', 'action': action})
    elif tool_name == 'superdoc_format':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'inline':
            return execute('doc.format.apply', rest)
        elif action == 'set_style':
            return execute('doc.styles.paragraph.setStyle', rest)
        elif action == 'set_alignment':
            return execute('doc.format.paragraph.setAlignment', rest)
        elif action == 'set_indentation':
            return execute('doc.format.paragraph.setIndentation', rest)
        elif action == 'set_spacing':
            return execute('doc.format.paragraph.setSpacing', rest)
        elif action == 'set_flow_options':
            return execute('doc.format.paragraph.setFlowOptions', rest)
        elif action == 'set_direction':
            return execute('doc.format.paragraph.setDirection', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_format: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_format', 'action': action})
    elif tool_name == 'superdoc_create':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'paragraph':
            return execute('doc.create.paragraph', rest)
        elif action == 'heading':
            return execute('doc.create.heading', rest)
        elif action == 'table':
            return execute('doc.create.table', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_create: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_create', 'action': action})
    elif tool_name == 'superdoc_list':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'insert':
            return execute('doc.lists.insert', rest)
        elif action == 'create':
            return execute('doc.lists.create', rest)
        elif action == 'attach':
            return execute('doc.lists.attach', rest)
        elif action == 'detach':
            return execute('doc.lists.detach', rest)
        elif action == 'delete':
            return execute('doc.lists.delete', rest)
        elif action == 'indent':
            return execute('doc.lists.indent', rest)
        elif action == 'outdent':
            return execute('doc.lists.outdent', rest)
        elif action == 'merge':
            return execute('doc.lists.merge', rest)
        elif action == 'split':
            return execute('doc.lists.split', rest)
        elif action == 'set_level':
            return execute('doc.lists.setLevel', rest)
        elif action == 'set_value':
            return execute('doc.lists.setValue', rest)
        elif action == 'continue_previous':
            return execute('doc.lists.continuePrevious', rest)
        elif action == 'set_type':
            return execute('doc.lists.setType', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_list: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_list', 'action': action})
    elif tool_name == 'superdoc_comment':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'create':
            return execute('doc.comments.create', rest)
        elif action == 'update':
            return execute('doc.comments.patch', rest)
        elif action == 'delete':
            return execute('doc.comments.delete', rest)
        elif action == 'get':
            return execute('doc.comments.get', rest)
        elif action == 'list':
            return execute('doc.comments.list', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_comment: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_comment', 'action': action})
    elif tool_name == 'superdoc_track_changes':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'list':
            return execute('doc.trackChanges.list', rest)
        elif action == 'decide':
            return execute('doc.trackChanges.decide', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_track_changes: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_track_changes', 'action': action})
    elif tool_name == 'superdoc_search':
        return execute('doc.query.match', args)
    elif tool_name == 'superdoc_mutations':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'preview':
            return execute('doc.mutations.preview', rest)
        elif action == 'apply':
            return execute('doc.mutations.apply', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_mutations: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_mutations', 'action': action})
    elif tool_name == 'superdoc_table':
        action = args.get('action')
        rest = {k: v for k, v in args.items() if k != 'action'}
        if action == 'delete':
            return execute('doc.tables.delete', rest)
        elif action == 'set_layout':
            return execute('doc.tables.setLayout', rest)
        elif action == 'insert_row':
            return execute('doc.tables.insertRow', rest)
        elif action == 'delete_row':
            return execute('doc.tables.deleteRow', rest)
        elif action == 'set_row':
            return execute('doc.tables.setRowHeight', rest)
        elif action == 'set_row_options':
            return execute('doc.tables.setRowOptions', rest)
        elif action == 'insert_column':
            return execute('doc.tables.insertColumn', rest)
        elif action == 'delete_column':
            return execute('doc.tables.deleteColumn', rest)
        elif action == 'set_column':
            return execute('doc.tables.setColumnWidth', rest)
        elif action == 'merge_cells':
            return execute('doc.tables.mergeCells', rest)
        elif action == 'unmerge_cells':
            return execute('doc.tables.unmergeCells', rest)
        elif action == 'set_cell':
            return execute('doc.tables.setCellProperties', rest)
        elif action == 'set_cell_text':
            return execute('doc.tables.setCellText', rest)
        elif action == 'set_shading':
            return execute('doc.tables.setShading', rest)
        elif action == 'set_style_options':
            return execute('doc.tables.applyStyle', rest)
        elif action == 'set_borders':
            return execute('doc.tables.setBorders', rest)
        elif action == 'set_options':
            return execute('doc.tables.setTableOptions', rest)
        else:
            raise SuperDocError(f'Unknown action for superdoc_table: {action}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': 'superdoc_table', 'action': action})
    else:
        raise SuperDocError(f'Unknown intent tool: {tool_name}', code='TOOL_DISPATCH_NOT_FOUND', details={'toolName': tool_name})
